#pragma once

// Generated by uitk from "title" -- do not edit by hand.

// NOTE: charmap_generic must already be in scope here.

#include <intsh>
#include <platform-nes/types.hpp>
#include <platform-nes/video.hpp>
#include <platform-nes/extras/ui/text.hpp>
#include <new>
#include <platform-nes/extras/ui/singlechoice.hpp>

using namespace br0::intsh;

namespace gen::title {

inline constexpr auto GameTitle_row0 = ::tech::nes_str::encode<charmap_generic>("SUPER MARY");
inline constexpr auto GameTitle_row1 = ::tech::nes_str::encode<charmap_generic>("SISTERS");

NI void Draw_GameTitle();

inline constexpr auto NewGame_row0 = ::tech::nes_str::encode<charmap_generic>("NEW GAME");

NI void Draw_NewGame();

inline constexpr auto Continue_row0 = ::tech::nes_str::encode<charmap_generic>("CONTINUE");

NI void Draw_Continue();

inline constexpr auto Options_row0 = ::tech::nes_str::encode<charmap_generic>("OPTIONS");

NI void Draw_Options();

// SingleChoice: TitleOptions
inline atomic vec2<u16> TitleOptions_options[3];
alignas(ui::choice::SingleChoice) inline u8 TitleOptions_storage[sizeof(ui::choice::SingleChoice)];
inline ui::choice::SingleChoice& TitleOptions = reinterpret_cast<ui::choice::SingleChoice&>(TitleOptions_storage);
inline AI void Make_TitleOptions() {
    TitleOptions_options[0] = vec2<u16>{static_cast<u16>((((((video::viewport_tx() >> 1) << 1) - 1) - 8) + 32)), static_cast<u16>((1 + 30))};
    TitleOptions_options[1] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 1) + 30))};
    TitleOptions_options[2] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 2) + 30))};
    new (&TitleOptions) ui::choice::SingleChoice(3, 0);
}

}  // namespace gen::title
