// Generated by uitk from "title" -- do not edit by hand.

#include "title.hpp"

namespace gen::title {

TITLE void Draw_GameTitle(void) {
    ppu::WriteFromBufferToNameTable(0x2c21, SIZED_OBJ(GameTitle_row0), 0);
    ppu::WriteFromBufferToNameTable(0x2c42, SIZED_OBJ(GameTitle_row1), 0);
}

TITLE void Draw_NewGame(void) {
    ppu::WriteFromBufferToNameTable(0x2c37, SIZED_OBJ(NewGame_row0), 0);
}

TITLE void Draw_Continue(void) {
    ppu::WriteFromBufferToNameTable(0x2c57, SIZED_OBJ(Continue_row0), 0);
}

TITLE void Draw_Options(void) {
    ppu::WriteFromBufferToNameTable(0x2c77, SIZED_OBJ(Options_row0), 0);
}

}  // namespace gen::title
