// Generated by uitk from "title" -- do not edit by hand.

#include "title.hpp"

namespace gen::title {

TITLE void Draw_GameTitle(void) {
    static const char row0[] = "Super Mary";
    ppu::WriteFromBufferToNameTable(0x2c21, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
    static const char row1[] = "Sisters";
    ppu::WriteFromBufferToNameTable(0x2c42, reinterpret_cast<const u8*>(row1), sizeof(row1) - 1, 0);
}

TITLE void Draw_NewGame(void) {
    static const char row0[] = "New Game";
    ppu::WriteFromBufferToNameTable(0x2c37, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
}

TITLE void Draw_Continue(void) {
    static const char row0[] = "Continue";
    ppu::WriteFromBufferToNameTable(0x2c57, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
}

TITLE void Draw_Options(void) {
    static const char row0[] = "Options";
    ppu::WriteFromBufferToNameTable(0x2c77, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
}

}  // namespace gen::title
