#pragma once

// Generated by uitk from "title" -- do not edit by hand.

// NOTE: charmap_generic must already be in scope wherever this header is included -- same requirement as any other CHARMAP consumer (see technology.hpp's CHARMAP macro).

#include <platform-nes/types.hpp>
#include <platform-nes/video.hpp>
#include <platform-nes/extras/ui/text.hpp>
#include <new>
#include <platform-nes/extras/ui/singlechoice.hpp>

namespace gen::title {

inline constexpr auto GameTitle_row0 = ::tech::nes_str::encode<charmap_generic>("Super Mary");
inline constexpr auto GameTitle_row1 = ::tech::nes_str::encode<charmap_generic>("Sisters");

void Draw_GameTitle(void);

inline constexpr auto NewGame_row0 = ::tech::nes_str::encode<charmap_generic>("New Game");

void Draw_NewGame(void);

inline constexpr auto Continue_row0 = ::tech::nes_str::encode<charmap_generic>("Continue");

void Draw_Continue(void);

inline constexpr auto Options_row0 = ::tech::nes_str::encode<charmap_generic>("Options");

void Draw_Options(void);

inline constexpr auto Textbox5_row0 = ::tech::nes_str::encode<charmap_generic>("Quit");

void Draw_Textbox5(void);

// SingleChoice: TitleOptions
inline vec2<u16> TitleOptions_options[4];
inline alignas(ui::option::SingleChoice) unsigned char TitleOptions_storage[sizeof(ui::option::SingleChoice)];
inline ui::option::SingleChoice& TitleOptions = reinterpret_cast<ui::option::SingleChoice&>(TitleOptions_storage);
inline AI void Make_TitleOptions() {
    TitleOptions_options[0] = vec2<u16>{static_cast<u16>((((((video::viewport_tx() >> 1) << 1) - 1) - 8) + 32)), static_cast<u16>((1 + 30))};
    TitleOptions_options[1] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 1) + 30))};
    TitleOptions_options[2] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 2) + 30))};
    TitleOptions_options[3] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 3) + 30))};
    new (&TitleOptions) ui::option::SingleChoice(4, 0);
}

}  // namespace gen::title
