#pragma once

// Generated by uitk from "title" -- do not edit by hand.

#include <platform-nes/types.hpp>
#include <platform-nes/video.hpp>
#include <platform-nes/extras/ui/text.hpp>
#include <new>
#include <platform-nes/extras/ui/singlechoice.hpp>

namespace gen::title {

void Draw_GameTitle(void);

void Draw_NewGame(void);

void Draw_Continue(void);

void Draw_Options(void);

void Draw_Textbox5(void);

// SingleChoice: TitleOptions
inline vec2<u16> TitleOptions_options[4];
inline alignas(ui::option::SingleChoice) unsigned char TitleOptions_storage[sizeof(ui::option::SingleChoice)];
inline ui::option::SingleChoice& TitleOptions = reinterpret_cast<ui::option::SingleChoice&>(TitleOptions_storage);
inline AI void Make_TitleOptions() {
    TitleOptions_options[0] = vec2<u16>{static_cast<u16>((((((video::viewport_tx() >> 1) << 1) - 1) - 8) + 32)), static_cast<u16>((1 + 30))};
    TitleOptions_options[1] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 1) + 30))};
    TitleOptions_options[2] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 2) + 30))};
    TitleOptions_options[3] = vec2<u16>{static_cast<u16>((23 + 32)), static_cast<u16>(((1 + 3) + 30))};
    new (&TitleOptions) ui::option::SingleChoice(4, 0);
}

}  // namespace gen::title
