// Generated by uitk from "title" -- do not edit by hand.

#include "title.hpp"

namespace gen::title {

void Draw_GameTitle(void) {
    static const char row0[] = "Super Mary";
    ppu::WriteFromBufferToNameTable(vec2<u16>{33, 31}, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
    static const char row1[] = "Sisters";
    ppu::WriteFromBufferToNameTable(vec2<u16>{34, 32}, reinterpret_cast<const u8*>(row1), sizeof(row1) - 1, 0);
}

void Draw_NewGame(void) {
    static const char row0[] = "New Game";
    ppu::WriteFromBufferToNameTable(vec2<u16>{55, 31}, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
}

void Draw_Continue(void) {
    static const char row0[] = "Continue";
    ppu::WriteFromBufferToNameTable(vec2<u16>{55, 32}, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
}

void Draw_Options(void) {
    static const char row0[] = "Options";
    ppu::WriteFromBufferToNameTable(vec2<u16>{55, 33}, reinterpret_cast<const u8*>(row0), sizeof(row0) - 1, 0);
}

}  // namespace gen::title
