#pragma once

// Generated by uitk from "title" -- do not edit by hand.

// NOTE: charmap_generic must already be in scope wherever this header is included -- same requirement as any other CHARMAP consumer (see technology.hpp's CHARMAP macro).

#include <platform-nes/types.hpp>
#include <platform-nes/video.hpp>
#include <platform-nes/extras/ui/text.hpp>
#include <new>
#include <platform-nes/extras/ui/singlechoice.hpp>

namespace gen::title {

inline constexpr auto GameTitle_row0 = ::tech::nes_str::encode<charmap_generic>("Super Mary");
inline constexpr auto GameTitle_row1 = ::tech::nes_str::encode<charmap_generic>("Sisters");

void Draw_GameTitle(void);

inline constexpr auto NewGame_row0 = ::tech::nes_str::encode<charmap_generic>("New Game");

void Draw_NewGame(void);

inline constexpr auto Continue_row0 = ::tech::nes_str::encode<charmap_generic>("Continue");

void Draw_Continue(void);

inline constexpr auto Options_row0 = ::tech::nes_str::encode<charmap_generic>("Options");

void Draw_Options(void);

// SingleChoice: TitleOptions
inline alignas(ui::option::SingleChoice) unsigned char TitleOptions_storage[sizeof(ui::option::SingleChoice)];
inline ui::option::SingleChoice& TitleOptions = reinterpret_cast<ui::option::SingleChoice&>(TitleOptions_storage);
inline AI void Make_TitleOptions() {
    new (&TitleOptions) ui::option::SingleChoice(3, 0);
}

}  // namespace gen::title
