#pragma once

// Generated by uitk from "title" -- do not edit by hand.

#include <platform-nes/types.hpp>
#include <platform-nes/video.hpp>
#include <platform-nes/extras/ui/text.hpp>
#include <new>
#include <platform-nes/extras/ui/singlechoice.hpp>

namespace gen::title {

void Draw_GameTitle(void);

void Draw_NewGame(void);

void Draw_Continue(void);

void Draw_Options(void);

// SingleChoice: TitleOptions
inline alignas(ui::option::SingleChoice) unsigned char TitleOptions_storage[sizeof(ui::option::SingleChoice)];
inline ui::option::SingleChoice& TitleOptions = reinterpret_cast<ui::option::SingleChoice&>(TitleOptions_storage);
inline AI void Make_TitleOptions() {
    new (&TitleOptions) ui::option::SingleChoice(3, 0);
}

}  // namespace gen::title
