#pragma once

// Generated by uitk from "title" -- do not edit by hand.

// NOTE: charmap_generic must already be in scope here.

#include <intsh>
#include <platform-nes/types.hpp>
#include <platform-nes/video.hpp>
#include <platform-nes/extras/ui/text.hpp>
#include <new>
#include <platform-nes/extras/ui/singlechoice.hpp>

using namespace br0::intsh;

namespace gen::title {

inline constexpr auto GameTitle_row0 = ::tech::nes_str::encode<charmap_generic>("SUPER MARY");
inline constexpr auto GameTitle_row1 = ::tech::nes_str::encode<charmap_generic>("SISTERS");

NI void Draw_GameTitle();

inline constexpr auto NewGame_row0 = ::tech::nes_str::encode<charmap_generic>("NEW GAME");

NI void Draw_NewGame();

inline constexpr auto Continue_row0 = ::tech::nes_str::encode<charmap_generic>("CONTINUE");

NI void Draw_Continue();

inline constexpr auto Options_row0 = ::tech::nes_str::encode<charmap_generic>("OPTIONS");

NI void Draw_Options();

// SingleChoice: TitleOptions
alignas(ui::choice::SingleChoice) inline u8 TitleOptions_storage[sizeof(ui::choice::SingleChoice)];
inline ui::choice::SingleChoice& TitleOptions = reinterpret_cast<ui::choice::SingleChoice&>(TitleOptions_storage);
inline AI void Make_TitleOptions() {
    new (&TitleOptions) ui::choice::SingleChoice(3, 0);
}

}  // namespace gen::title
